[project]
name = "frenztoolkit-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "frenztoolkit>=0.2.0",
    "matplotlib>=3.9.4",
    "mne>=1.8.0",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "pip>=25.1",
]
